# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.proto import kuro_pb2 as common_dot_proto_dot_kuro__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/proto/kuro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub(object):
    """--- CORE BRAIN SERVICE (VM 1) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.stream_stream(
                '/kuro.BrainService/ChatStream',
                request_serializer=common_dot_proto_dot_kuro__pb2.UserMessage.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.BrainResponse.FromString,
                _registered_method=True)


class BrainServiceServicer(object):
    """--- CORE BRAIN SERVICE (VM 1) ---
    """

    def ChatStream(self, request_iterator, context):
        """Stream natural language from client to brain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.UserMessage.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.BrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuro.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuro.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """--- CORE BRAIN SERVICE (VM 1) ---
    """

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kuro.BrainService/ChatStream',
            common_dot_proto_dot_kuro__pb2.UserMessage.SerializeToString,
            common_dot_proto_dot_kuro__pb2.BrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub(object):
    """--- MEMORY SERVICE (VM 3) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContext = channel.unary_unary(
                '/kuro.MemoryService/GetContext',
                request_serializer=common_dot_proto_dot_kuro__pb2.ContextRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.ProposeMemory = channel.unary_unary(
                '/kuro.MemoryService/ProposeMemory',
                request_serializer=common_dot_proto_dot_kuro__pb2.MemoryProposal.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.MemoryStatus.FromString,
                _registered_method=True)
        self.UpdatePreference = channel.unary_unary(
                '/kuro.MemoryService/UpdatePreference',
                request_serializer=common_dot_proto_dot_kuro__pb2.PreferenceUpdate.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.MemoryStatus.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """--- MEMORY SERVICE (VM 3) ---
    """

    def GetContext(self, request, context):
        """Retrieve relevant behavioral atoms and personality snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeMemory(self, request, context):
        """Decides whether an interaction should be stored (VM 1 calls this)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePreference(self, request, context):
        """Updates specific preference weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContext,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.ContextRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.ContextResponse.SerializeToString,
            ),
            'ProposeMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeMemory,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.MemoryProposal.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.MemoryStatus.SerializeToString,
            ),
            'UpdatePreference': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePreference,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.PreferenceUpdate.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.MemoryStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuro.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuro.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """--- MEMORY SERVICE (VM 3) ---
    """

    @staticmethod
    def GetContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.MemoryService/GetContext',
            common_dot_proto_dot_kuro__pb2.ContextRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.MemoryService/ProposeMemory',
            common_dot_proto_dot_kuro__pb2.MemoryProposal.SerializeToString,
            common_dot_proto_dot_kuro__pb2.MemoryStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.MemoryService/UpdatePreference',
            common_dot_proto_dot_kuro__pb2.PreferenceUpdate.SerializeToString,
            common_dot_proto_dot_kuro__pb2.MemoryStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RagServiceStub(object):
    """--- RAG SERVICE (VM 2) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchKnowledge = channel.unary_unary(
                '/kuro.RagService/SearchKnowledge',
                request_serializer=common_dot_proto_dot_kuro__pb2.SearchRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.SearchResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """--- RAG SERVICE (VM 2) ---
    """

    def SearchKnowledge(self, request, context):
        """Semantic search for knowledge
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.SearchRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuro.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuro.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """--- RAG SERVICE (VM 2) ---
    """

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.RagService/SearchKnowledge',
            common_dot_proto_dot_kuro__pb2.SearchRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientExecutorStub(object):
    """--- CLIENT EXECUTOR SERVICE (Local Machine) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAction = channel.unary_unary(
                '/kuro.ClientExecutor/ExecuteAction',
                request_serializer=common_dot_proto_dot_kuro__pb2.ActionRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.RequestConfirmation = channel.unary_unary(
                '/kuro.ClientExecutor/RequestConfirmation',
                request_serializer=common_dot_proto_dot_kuro__pb2.ConfirmationRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.ConfirmationResponse.FromString,
                _registered_method=True)


class ClientExecutorServicer(object):
    """--- CLIENT EXECUTOR SERVICE (Local Machine) ---
    """

    def ExecuteAction(self, request, context):
        """Execute a secure, ID-mapped action
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestConfirmation(self, request, context):
        """Request confirmation for destructive tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.ActionRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.ActionResponse.SerializeToString,
            ),
            'RequestConfirmation': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestConfirmation,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.ConfirmationRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.ConfirmationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuro.ClientExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuro.ClientExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientExecutor(object):
    """--- CLIENT EXECUTOR SERVICE (Local Machine) ---
    """

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.ClientExecutor/ExecuteAction',
            common_dot_proto_dot_kuro__pb2.ActionRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestConfirmation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.ClientExecutor/RequestConfirmation',
            common_dot_proto_dot_kuro__pb2.ConfirmationRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.ConfirmationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """--- GLOBAL HEALTH SERVICE (Shared across VMs) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/kuro.HealthService/Check',
                request_serializer=common_dot_proto_dot_kuro__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/kuro.HealthService/Watch',
                request_serializer=common_dot_proto_dot_kuro__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.ClusterHealth.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """--- GLOBAL HEALTH SERVICE (Shared across VMs) ---
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.HealthCheckRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.HealthCheckRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.ClusterHealth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuro.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuro.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """--- GLOBAL HEALTH SERVICE (Shared across VMs) ---
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.HealthService/Check',
            common_dot_proto_dot_kuro__pb2.HealthCheckRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kuro.HealthService/Watch',
            common_dot_proto_dot_kuro__pb2.HealthCheckRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.ClusterHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OpsServiceStub(object):
    """--- OPS SERVICE (VM 4) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteSystemAction = channel.unary_unary(
                '/kuro.OpsService/ExecuteSystemAction',
                request_serializer=common_dot_proto_dot_kuro__pb2.ActionRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_kuro__pb2.ActionResponse.FromString,
                _registered_method=True)


class OpsServiceServicer(object):
    """--- OPS SERVICE (VM 4) ---
    """

    def ExecuteSystemAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteSystemAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSystemAction,
                    request_deserializer=common_dot_proto_dot_kuro__pb2.ActionRequest.FromString,
                    response_serializer=common_dot_proto_dot_kuro__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuro.OpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuro.OpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpsService(object):
    """--- OPS SERVICE (VM 4) ---
    """

    @staticmethod
    def ExecuteSystemAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuro.OpsService/ExecuteSystemAction',
            common_dot_proto_dot_kuro__pb2.ActionRequest.SerializeToString,
            common_dot_proto_dot_kuro__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
